server: 127.0.0.1
port: 443
websocket-path: "/websocket"
log:
  # path: ./client.log
  log-level: info
auth:
  user: user2
  password: passwd2
skip-cert-verify: true
hotkey:
  upload: Control+Alt+C
  download: Control+Alt+V

# auto: 自动获取剪贴板内容，并且上传到服务器，服务器也会自动下发内容到该客户端
# manual: 需要手动上传或者下载内容
mode: auto